name: autotag

on:
  push:
    branches:
      - "main"

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Auto Tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
          tag_prefix: ""
